spring:
  cloud:
    gateway: #网关
      routes: #路由
        #       模糊的路由放低优先级   /api/**-->模糊路由
        - id: reggie  #路由名
          uri: lb://reggie  #负载均衡到服务reggie
          predicates: #断言
            - Path=/** #前端项目 ,访问该路径会进入页面
          filters: #路径重写#http://localhost:88/ -->  http://localhost:8080/
            - RewritePath=/(?<segment>.*), /$\{segment}
        #            访问http://localhost:88/ --会转变为-->  http://localhost:8080/
        #将guliorder.xxxxx.club域名访问路由到瑞吉外卖服务
        - id: reggie  #路由名,nginx负载均衡
          uri: lb://reggie  #负载均衡到reggie服务
          predicates: #断言
            - Host=guliorder.xxxxxx.club #将guliorder.xxxxxx.club:8081/下的请求都转给reggie服务
#            例如:访问http://guliorder.xxxxx.club:8081/ 路由到http://localhost:8080/
####################################################################
        #将guliorder.sssss.club域名访问路由到瑞吉外卖服务
        - id: reggie  #路由名,nginx负载均衡
          uri: lb://reggie  #负载均衡到reggie服务
          predicates: #断言
            - Host=1f872a2261.zicp.vip #将1f872a2261.zicp.vip:8081/下的请求都转给reggie服务
#            例如:访问http://guliorder.xxxxx.club:8081/ 路由到http://localhost:8080/
####################################################################






















